export const urlBase = 'http://localhost:9011'
export const userService = urlBase + '/usuarios-srv/api'
export const productService = urlBase + '/productos-srv/api'
export const orderService = urlBase + '/pedidos-srv/api'
export const currentAccountService = urlBase + '/cta-cte-srv/api'
export const keycloakService = urlBase + '/usuarios/api/login'